'pip install' now works.
Fixes issue: https://github.com/sseemayer/Py2D/issues/11

'pip-install', for example using:

    pip install git+git://github.com/sseemayer/Py2D#egg=Py2D

would previously fail with:

    ModuleNotFoundError: No module named 'Cython'

because setup.py imports Cython at module level. Pip would read
setup.py before having installed anything, so third party packages
such as Cython are not available.

Modern versions of setuptools support a fix for this, as implemented
in this PR.

Instead of importing build_ext from Cython, we can now use
'setup_requires' to declare our install-time requirements.

So pip installing now works, and once done, `python setup.py build_ext`
works to build the Cython libraries.